# SPDX-FileCopyrightText: 2025-2026 caixw
#
# SPDX-License-Identifier: MIT

- pkg: "@cmfx/components"
  entrypoints:
      - entrypoint: "index.d.ts"
        types:
            - ChartProps
            - ChartRef
            - ChartAxisProps
            - ChartAxisPropsAxis
            - ChartAxisPropsSeries
            - ChartAxisRef
            - ChartPieProps
